# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Build

on:
    pull_request: null

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0

            -   run: composer install --no-progress --ignore-platform-reqs

            -
                name: Build
                run: |
                    # configure timezone: https://stackoverflow.com/a/27052708/1348344
                    export TZ=Europe/Prague
                    bin/console import --ansi -vvv
                    bin/console dump-static-site --ansi
                env:
                    MEETUP_COM_OAUTH_KEY: ${{ secrets.MEETUP_COM_OAUTH_KEY }}
                    MEETUP_COM_OAUTH_SECRET: ${{ secrets.MEETUP_COM_OAUTH_SECRET }}
