# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Build and Deploy

on:
    push:
        branches:
            - master
    schedule:
        # * is a special character in YAML so you have to quote this string
        # https://crontab.guru/every-12-hours
        - cron: '0 */12 * * *'

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            -
                uses: actions/checkout@v2
                with:
                    persist-credentials: false

            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 7.4

            -   run: composer install --no-progress --ansi

            # configure timezone: https://stackoverflow.com/a/27052708/1348344
            -   run: export TZ=Europe/Prague

            -   run: bin/console import --ansi
                env:
                    MEETUP_COM_OAUTH_KEY: ${{ secrets.MEETUP_COM_OAUTH_KEY }}
                    MEETUP_COM_OAUTH_SECRET: ${{ secrets.MEETUP_COM_OAUTH_SECRET }}

            -   run: bin/console dump-static-site --ansi

            # see https://github.com/JamesIves/github-pages-deploy-action
            -
                name: Deploy 🚀
                uses: JamesIves/github-pages-deploy-action@3.7.1
                with:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
                    BRANCH: gh-pages
                    FOLDER: output
                    CLEAN: true
