# see https://github.com/marketplace/actions/deploy-to-github-pages
name: Build

on:
    pull_request: null

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            # see https://github.com/shivammathur/setup-php
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2

            - run: composer install --no-progress

            - name: Build
              run: |
                  bin/console import --ansi
                  bin/console stenope:build
