name: Code Analysis

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    matrix:
        strategy:
            fail-fast: false
            matrix:
                actions:
                    -
                        name: Coding Standard
                        run: 'composer fix-cs'

                    -
                        name: 'PHPStan'
                        run: composer phpstan

                    -
                        name: 'Unit Tests'
                        run: vendor/bin/phpunit

                    -
                        name: 'Rector'
                        run: vendor/bin/rector process --dry-run --ansi

                    -
                        name: 'Dead Groups'
                        run: 'bin/console validate-dead-groups --ansi'

        name: ${{ matrix.actions.name }}
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2

            # see https://github.com/shivammathur/setup-php
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    # needed by phpunit
                    extensions: mbstring

            -   run: composer install --no-progress --ansi --ignore-platform-reqs

            -   run: ${{ matrix.actions.run }}
