name: Duplicated Groups

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    duplicated_groups:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none

            -   run: composer install --no-progress --ignore-platform-reqs

            -   run: bin/console validate-groups
                env:
                    MEETUP_COM_OAUTH_KEY: ${{ secrets.MEETUP_COM_OAUTH_KEY }}
                    MEETUP_COM_OAUTH_SECRET: ${{ secrets.MEETUP_COM_OAUTH_SECRET }}
