name: Duplicated Groups

on:
    pull_request: null
    push:
        branches:
            - main

jobs:
    duplicated_groups:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: 8.2
                  coverage: none

            - run: composer install --no-progress

            - run: bin/console validate-groups --ansi
